export const SERVER_API = 'http://localhost:5000/'
export const CLIENT_API = 'https://corp.ru/'
// URL
export const REGISTRATION_URL = 'api/user/registration'
export const LOGIN_URL = 'api/user/login'
export const LOGOUT_URL = 'api/user/logout'
export const REFRESH_URL = 'api/user/refresh'
export const USERDATA_URL = 'api/user/data/'
export const CHANGELOGIN_URL = 'api/user/changeLogin'
export const CHANGEPASSWORD_URL = 'api/user/changePassword'
export const CHANGENICKNAME_URL = 'api/user/changeNickname'
export const CHANGEGENDER_URL = 'api/user/changeGender'
export const CHANGEFIRSTNAME_URL = 'api/user/changeFirstname'
export const CHANGELASTNAME_URL = 'api/user/changeLastname'
export const CHANGEPHOTO_URL = 'api/user/changePhoto'
export const CHANGESTATUS_URL = 'api/user/changeStatus'
export const SEARCHUSER_URL = 'api/user/searchUser'
export const CHATLIST_URL = 'api/communication/chatList'
export const CHAT_URL = 'api/communication/chat/'
export const SENDMESSAGE_URL = 'api/communication/createMessage'
export const CREATECHAT_URL = 'api/communication/createChat'
export const CREATECONVERSATION_URL = 'api/communication/createConversation'
// ROUTES
export const REGISTRATION_ROUTE = '/registration'
export const AUTHORIZATION_ROUTE = '/auth'
export const PROFILE_ROUTE = '/:nickname'
export const SETTINGS_ROUTE = '/settings'
export const EDITPROFILE_ROUTE= '/edit'
export const ERROR_ROUTE = '/error'
export const CHAT_ROUTE = '/chat/:id'
export const CHATLIST_ROUTE = '/chats'
export const CREATE_ROUTE = '/create'
export const DEFAULT_ROUTE = '/'

